# Generated by Django 4.0.6 on 2023-08-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_theater_movie_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(auto_created=True, default=None, null=True),
        ),
    ]
