# Generated by Django 4.0.6 on 2023-10-07 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_booking_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theaters', to='movies.movie'),
        ),
    ]
